### ISSUE TITLE
I get this error when running the script...

### ISSUE THREAD

**Issue by jeffshead** [matidau/Z-Push#10]
```
FAILED: apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confnew install munin munin-node libcgi-fast-perl
-----------------------------------------
E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 18816 (apt-get)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
```
Is this anything to worry about or is there something I need to do and then reinstall?

**Comment by matidau** [comment]
This looks like the package manager is still running. What do you get back running apt-get?

Restarting the machine/vm might be a quick way to resolve.

**Comment by jeffshead** [comment]
Thanks for taking the time to respond!

The first thing that I tried was rebooting the server and running the script a second time but this is all I get:

```
root@mail:~# curl -s https://mat.id.au/zpushpatch.sh | sudo bash
Z-Push setup script is not pulling version 2.6.2.
It might have already been patched.
Check that your Z-Push needs updating.
root@mail:~#
```

Z-Push seems to be working but should I try to "patch" the system a second time? If so, what's the command to force the script to run?

**Comment by matidau** [comment]
After the script has run once it patches the MailinaBox zpush.sh script, and then runs the MailinaBox set up again.

Your original error message was related to the MailinaBox having another problem unrelated to the zpush setup.

This thread shows that your error message has had similar occurrences for a while. 
https://discourse.mailinabox.email/t/v-0-44-upgrade-munin-apt-get-failed/6030

To ensure MailinaBox is running correctly try running MailinaBox setup again, maybe after waiting a while to ensure there are no errors or packages waiting to be updated.

If you are on v60/v61 of MailinaBox and Z-Push is working then I would say that zpush has been correctly setup.

Cheers,
Mat

**Comment by jeffshead** [comment]
No errors the second time around.

Thanks again!
