### ISSUE TITLE
 Uncaught Error: Call to undefined function mb_detect_encoding() in /usr/share/z-push/lib/utils/utils.php:1193

### ISSUE THREAD

**Issue by derritter88** [matidau/Z-Push#8]
Hello there,

I recently stumbled accros your comment on https://sourceforge.net/p/zimbrabackend/support-requests/185/ and gave your fork a try.
Unfortunatley it's not working due to following exception:

```
07/03/2023 19:34:48 [3407278] [FATAL] [email.address@domain.tld] Fatal error: /usr/share/z-push/lib/utils/utils.php:1193 - Uncaught Error: Call to undefined function mb_detect_encoding() in /usr/share/z-push/lib/utils/utils.php:1193
Stack trace:
#0 /usr/share/z-push/lib/request/request.php(291): Utils::ConvertAuthorizationToUTF8()
#1 /usr/share/z-push/index.php(61): Request::ProcessHeaders()
#2 {main}
  thrown (1)
```

I have tried to use it with PHP8.2-FPM

**Comment by matidau** [comment]
Hi derritter88,

I think Utils::ConvertAuthorizationToUTF8 relies on the package php-mbstring. 

Have you tried to install this package? Command below for debian based systems. 

`apt-get install php-mbstring`

**Comment by derritter88** [comment]
Yeah, totally right - my mistake.
I haven't installed all needed packages.
