### ISSUE TITLE
iOS 16.4 no longer syncs

### ISSUE THREAD

**Issue by derritter88** [matidau/Z-Push#9]
Hello there,

after the upgrade to the latest iOS 16.4 version my phone is no longer synchronizing.
I can see following exception at the z-push log:

```

02/04/2023 10:33:21 [407232] [WARN] [email@hks-projekt.at] Zimbra->GetUserInfo():   Overriding ZIMBRA_URL [https://mail.hks-projekt.at] from config.php with ZIMBRA publicURL [https://mail.hks-projekt.at:8443]
02/04/2023 10:33:21 [407232] [WARN] [email@hks-projekt.at] Zimbra->GetUserInfo():   Overriding  Logon URL [https://mail.hks-projekt.at/service/soap/] with ZIMBRA soapURL [https://mail.hks-projekt.at:8443/service/soap/]
02/04/2023 10:33:21 [428386] [WARN] [email@hks-projekt.at] Zimbra->GetUserInfo():   Overriding ZIMBRA_URL [https://mail.hks-projekt.at] from config.php with ZIMBRA publicURL [https://mail.hks-projekt.at:8443]
02/04/2023 10:33:21 [428386] [WARN] [email@hks-projekt.at] Zimbra->GetUserInfo():   Overriding  Logon URL [https://mail.hks-projekt.at/service/soap/] with ZIMBRA soapURL [https://mail.hks-projekt.at:8443/service/soap/]
02/04/2023 10:33:21 [428386] [WARN] [email@hks-projekt.at] SyncObject->Check(): Unmet condition in object from type SyncProvisioning: parameter 'maxattsize' is LOWER than '-1'. Check failed!
02/04/2023 10:33:21 [428386] [FATAL] [email@hks-projekt.at] FatalException: Invalid policies! - code: 0 - file: /usr/share/z-push/lib/request/provisioning.php:220
02/04/2023 10:33:21 [428386] [FATAL] [email@hks-projekt.at] WBXML 10K debug data: AwFqAAAORQASVkhXA2lQaG9uZTE0QzcAAVoDaU9TIDE2LjQgMjBFMjQ3AAFgA2lPUy8xNi40ICgyMEUyNDcpIGV4Y2hhbmdlc3luY2QvMS4wAAFZA2lQaG9uZSAxNAABWwNkZS1BVAABAQEADkZHSANNUy1FQVMtUHJ
vdmlzaW9uaW5nLVdCWE1MAAEBAQE=
02/04/2023 10:33:21 [428386] [FATAL] [email@hks-projekt.at] Exception: (FatalException) - Invalid policies!
```

**Comment by derritter88** [comment]
Android devices are still syncing.

**Comment by matidau** [comment]
Hi derritter88,

Can you check what the value of `maxattsize` is in `src/policies.ini`?

**Comment by derritter88** [comment]
Hello @matidau ,

the values would be:
`maxattsize = '' `

So it's empty.

**Comment by derritter88** [comment]
Not sure if this is relevant or not but I have replaced the last official repo installation with yours to be compatible for PHP8.x - so I softlinked the config files from `/etc/z-push/` to the `/usr/share/z-push` folder as it was previously with the Z-Push PHP 7.4 version.

But I don't think that this should be the origin of the error.

**Comment by matidau** [comment]
In this case it is likely the cause. That value should be
`maxattsize = '-1'`
As per https://github.com/matidau/Z-Push/blob/php8.x/src/policies.ini

The empty string was the default value in the previous kopano version, but setting this to empty is not supported in the current version.

There are no other changes to this file so updating it to -1 should fix your problem.

Cheers,
Mat

**Comment by derritter88** [comment]
Thanks a lot - that fixed it :-)

**Comment by matidau** [comment]
No problems :)

**Comment by cvhoangpt** [comment]
> No problems :)

hi matidau,
zpush 2.7.0, I cannot sync from ios 16 or 17, some log are retry to provisioning command, what can I do

**Comment by matidau** [comment]
Hi @cvhoangpt 

I've created an issue in the main repo https://github.com/Z-Hub/Z-Push/issues/43

Cheers,
Mat
